#!/bin/bash
DIR="$(dirname "$([[ -L "$0" ]] && readlink "$0" || dirname "$0")")"

COMMAND="$DIR/$1.gxy"
shift

if [[ -f $COMMAND ]]; then
	$COMMAND "$@"
else
	echo "Unknown command: $COMMAND"
	exit 1
fi
